version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  covariate_check_ages_40_60_80:
    run: r:latest analysis/covariate_check.R 40_60_80
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        covariate_check_ages: output/covariate_check_ages_40_60_80.csv